#!/usr/bin/env bash
# Sets up nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "<h1>CECI N'EST PAS UNE PAGE</h1>" > /var/www/html/Error404/Do_You_Even_Locate_Bro_404.html
sudo sed -i "46i \\\terror_page 404 \/Do_You_Even_Locate_Bro_404.html;\n\tlocation = \/Do_You_Even_Locate_Bro_404.html {\n\t\troot \/var\/www\/html/Error404;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
service nginx start
