#!/usr/bin/env bash
# Sets up nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/Error404/404_generic.html
sudo sed -i "46i \\\terror_page 404 \/404_generic.html;\n\tlocation = \/404_generic.html {\n\t\troot \/var\/www\/html/Error404;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
service nginx start
