#!/usr/bin/env bash
# install HAproxy load balancer

sudo apt upgrade
sudo apt-get install haproxy -y

echo "
frontend main
    bind *:80
    mode http
    default_backend web-server
" >> /etc/haproxy/haproxy.cfg

echo "
backend web-server
	balance roundrobin
	server gc-1196-web-01-1584940402 35.237.196.81:80 check
	server 1196-web-02   3.93.170.20:80 check
" >> /etc/haproxy/haproxy.cfg


echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
