#!/usr/bin/env bash
# install HAproxy load balancer

sudo apt upgrade
sudo apt-get install haproxy -y

sudo echo "
frontend main
    bind *:80
    mode http
    default_backend back-route
" >> /etc/haproxy/haproxy.cfg

sudo echo "
backend back-route
	balance roundrobin
	server 1196-web-01 35.237.196.81:80 check
	server 1196-web-02   3.93.170.20:80 check
" >> /etc/haproxy/haproxy.cfg


sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
