#!/usr/bin/env bash
# FizzBuzz exercise

for ((i = 1; i <= 100; i++))
do
     if [[ $((i % 3)) -ne 0 ]] && [[ $((i % 5)) -ne 0 ]]
    then
	echo "$i"
    else
	if [[ $((i % 15)) -eq 0 ]]
	then
	    echo "FizzBuzz"
	elif [[ $((i % 3)) -eq 0 ]]
	then
	    echo "Fizz"
	elif [[ $((i % 5)) -eq 0 ]]
	then
	    echo "Buzz"
        fi
    fi
done
