#!/usr/bin/env bash
# This script is displaying minutes from 1-59 and the hour

i=1
j=0
while [[ $i -le 60 ]]
do
    if [ $j -eq 0 ] && [ $i -eq 1 ]
    then
	echo "Hour: 0"
    fi

    echo $i

    if [ $i -eq 59 ]
    then
	j=$((j + 1))
	echo "Hour: $j"
	if [ $j -eq 12 ]
	then
	    break
	fi
    fi

    i=$((i + 1))

    if [ $i -eq 60 ]
    then
	i=1
    fi
done
