#!/usr/bin/env bash
#Run process as another user
sudo chmod a+rwx /etc/nginx/nginx.conf
sudo killall apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx -c 'service nginx restart'
